baseurl: "/"
title: "Universal"
params:
  logo: 'images/logo.svg'
menus:
  main:
    - identifier: home
      weight: 1
      url: /
      title: Home
sass:
  input_file: sass/main.scss.njk
  output_file: assets/css/main.css
  indentWidth: 4
  outputStyle: nested
  precision: 10
